// This file was generated by executing this statement: wav2c
// screamAndDie48k.wav
//#define ZOMBIE_WAV_SAMPLE_RATE 480000
#define ZOMBIE_WAV_BITS_PER_SAMPLE 16
#define ZOMBIE_WAV_NUMBER_OF_SAMPLES 176128


extern uint16_t zombieSound[];